apiVersion: apps/v1
kind: Deployment
metadata:
  name: horoscope-bot
  namespace: horoscope-bot
  labels:
    app: horoscope-bot
    version: v1.0.0
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: horoscope-bot
  template:
    metadata:
      labels:
        app: horoscope-bot
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: horoscope-bot
          image: your-registry/horoscope-bot:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 3000
              name: health-port
              protocol: TCP

          env:
            - name: NODE_ENV
              value: "production"
            - name: HEALTH_PORT
              value: "3000"
            - name: XDG_RUNTIME_DIR
              value: "/tmp/xdg_runtime_dir"

          envFrom:
            - secretRef:
                name: horoscope-config

          volumeMounts:
            - name: wwebjs-auth
              mountPath: /app/.wwebjs_auth
            - name: logs
              mountPath: /app/logs

          livenessProbe:
            httpGet:
              path: /health
              port: health-port
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 15
            failureThreshold: 5

          readinessProbe:
            httpGet:
              path: /ready
              port: health-port
            initialDelaySeconds: 120
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 5

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL

      volumes:
        - name: wwebjs-auth
          persistentVolumeClaim:
            claimName: horoscope-auth-pvc
        - name: logs
          persistentVolumeClaim:
            claimName: horoscope-logs-pvc

      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: horoscope-bot
  namespace: horoscope-bot
  labels:
    app: horoscope-bot
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: health-port
      protocol: TCP
      name: health
  selector:
    app: horoscope-bot

---
# PVC usando el local-path provisioner por defecto de k3s
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: horoscope-auth-pvc
  namespace: horoscope-bot
  labels:
    app: horoscope-bot
    component: auth
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: horoscope-logs-pvc
  namespace: horoscope-bot
  labels:
    app: horoscope-bot
    component: logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path

---
apiVersion: v1
kind: Secret
metadata:
  name: horoscope-config
  namespace: horoscope-bot
  labels:
    app: horoscope-bot
type: Opaque
stringData:
  HOROSCOPES_SIGNS: "sign1,sign2"
  RECIPIENT_PHONE: "CHANGE_ME@c.us" # ⚠️  CAMBIAR POR EL NÚMERO REAL
  SEND_TIME: "08:00"
  TZ: "America/Santo_Domingo" # Ajustado para RD
  SEND_ON_STARTUP: "false"
  WEEKLY_ENABLED: "false"
  LOG_MESSAGES: "true"
